# Generated by Django 4.1.4 on 2024-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_firstname", models.CharField(max_length=100)),
                ("sender_lastname", models.CharField(max_length=100)),
                ("sender_email", models.EmailField(max_length=100)),
                ("message", models.CharField(max_length=1000)),
                ("come_time", models.DateTimeField()),
            ],
        ),
    ]
